from pydantic import BaseModel, Field


class CandidateScores(BaseModel):
    candidate_id: str = Field(..., description="Unique identifier for the candidate")
    job_id: str = Field(..., description="Unique identifier for the job post")
    completion_score: float | None = Field(
        None, description="Score representing the candidate's resume completion level"
    )
    rule_based_score: float | None = Field(
        None,
        description="Score based on rule-based evaluation of the candidate's resume",
    )
    skill_match_score: float | None = Field(
        None,
        description="Score representing candiadte skill match",
    )
    ai_score: float | None = Field(
        None, description="Score generated by AI models evaluating the candidate"
    )
    ai_explanation: str | None = Field(
        None,
        description="Explanation for the AI-generated score",
    )
    aggregate_score: float | None = Field(
        None,
        description="Candidates overall score",
    )


class CandidateFlags(BaseModel):
    candidate_id: str = Field(..., description="Unique identifier for the candidate")
    job_id: str = Field(..., description="Unique identifier for the jobpost")
    flags: list[str] | None = Field(
        None,
        description="List of flags raised for the candidate",
    )


class CandidateMissingFields(BaseModel):
    candidate_id: str = Field(..., description="Unique identifier for the candidate")
    job_id: str = Field(..., description="Unique identifier for the job post")
    missing_fields: list[str] | None = Field(
        None,
        description="missed required fields from candidate resume",
    )


class ShortlistCandidate(BaseModel):
    job_candidate_id: str = Field(
        ..., description="Unique identifier for the job candidate"
    )
    job_id: str = Field(..., description="Unique identifier for the job post")
    candidate_id: str = Field(..., description="Unique identifier for the candidate")
    recruiter_notes: str | None = Field(
        None, description="Notes added by the recruiter regarding the candidate"
    )
    reviewed_by: str | None = Field(
        None,
        description="Unique identifier of the recruiter who reviewed the candidate",
    )


class JobShortlist(BaseModel):
    job_id: str = Field(..., description="Unique identifier for the job post")
    shortlisted_candidates: list[ShortlistCandidate] | None = Field(
        None, description="List of candidates for a job post"
    )


class NoteRequest(BaseModel):
    note: str = Field(..., description="Note content to be added for the candidate")
